import { Box, Typography } from "@mui/material";
import Head from "next/head";
import HomePage from "../components/home/home-page";
import Main from "../components/layout/main";
export default function Home() {
	return (
		<Box>
			<Head>
				<title>Sell Ecommerce | Next JS</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomePage />
		</Box>
	);
}

Home.Layout = Main;
